/* Create the schema for uor tables */
/* Date: YYYY-MM-DD */
DROP TABLE OBSERVACION_ESPECIE;
DROP TABLE ESPECIE;
DROP TABLE OBSERVACION;
DROP TABLE HABITAT;
DROP TABLE ESTADO_CONSERVACION;
DROP TABLE AREA_AMENAZADA;
DROP TABLE AMENAZA_RIESGO;
DROP TABLE ACTIVIDAD_CONSERVACION;
DROP TABLE REGISTRO_INDICADOR;
DROP TABLE INDICADOR_BIODIVERSIDAD;
DROP TABLE AREA_PROTEGIDA;
DROP TABLE TIPO_ECOSISTEMA;

CREATE TABLE TIPO_ECOSISTEMA (
    ID VARCHAR2(8) NOT NULL,
    TIPO_ECOSISTEMA VARCHAR2(40) UNIQUE,
    PRIMARY KEY (ID)
);

CREATE TABLE AREA_PROTEGIDA (
    ID VARCHAR2(8) NOT NULL,
    NOMBRE VARCHAR2(100),
    EXTENSION NUMBER(10, 2) CHECK (EXTENSION > 0),
    FECHA_CREACION DATE CHECK (FECHA_CREACION > TO_DATE('1800-01-01', 'YYYY-MM-DD') AND FECHA_CREACION <= TO_DATE('2024-05-01', 'YYYY-MM-DD')),
    UBICACION_LATITUD NUMBER(9, 6) CHECK (UBICACION_LATITUD >= -90 AND UBICACION_LATITUD <= 90),
    UBICACION_LONGITUD NUMBER(10, 6) CHECK (UBICACION_LONGITUD >= -180 AND UBICACION_LONGITUD <= 180),
    TIPOECOSISTEMA_ID VARCHAR2(8),
    PRIMARY KEY(ID),
    FOREIGN KEY (TIPOECOSISTEMA_ID) REFERENCES TIPO_ECOSISTEMA(ID) ON DELETE SET NULL
);

CREATE TABLE INDICADOR_BIODIVERSIDAD (
    ID VARCHAR2(8) NOT NULL,
	NOMBRE VARCHAR2(100) UNIQUE,
	DESCRIPCION VARCHAR2(300),
	PRIMARY KEY (ID)
);

CREATE TABLE REGISTRO_INDICADOR (
    ID VARCHAR2(8) NOT NULL,
	VALOR_INDICADOR VARCHAR2(8),
	FECHA_REGISTRO DATE CHECK (FECHA_REGISTRO > TO_DATE('1800-01-01', 'YYYY-MM-DD') AND FECHA_REGISTRO <= TO_DATE('2024-05-01', 'YYYY-MM-DD')),
	NOTAS VARCHAR2(250),
	AREA_PROTEGIDA_ID VARCHAR2(8),
	INDICADOR_BIODIVERSIDAD_ID VARCHAR2(8),
	PRIMARY KEY (ID),
	FOREIGN KEY (AREA_PROTEGIDA_ID) REFERENCES AREA_PROTEGIDA(ID) ON DELETE SET NULL,
	FOREIGN KEY (INDICADOR_BIODIVERSIDAD_ID) REFERENCES INDICADOR_BIODIVERSIDAD(ID) ON DELETE SET NULL
);

CREATE TABLE ACTIVIDAD_CONSERVACION (
    ID VARCHAR2(8) NOT NULL,
	NOMBRE VARCHAR2(100),
	DESCRIPCION VARCHAR2(300),
    FECHA_REALIZACION DATE CHECK (FECHA_REALIZACION > TO_DATE('1800-01-01', 'YYYY-MM-DD') AND FECHA_REALIZACION <= TO_DATE('2024-05-01', 'YYYY-MM-DD')),
	AREA_PROTEGIDA_ID VARCHAR2(8),
	PRIMARY KEY (ID),
	FOREIGN KEY (AREA_PROTEGIDA_ID) REFERENCES AREA_PROTEGIDA(ID) ON DELETE SET NULL
);

CREATE TABLE AMENAZA_RIESGO (
    ID VARCHAR2(8) NOT NULL,
	NOMBRE VARCHAR2(100),
	DESCRIPCION VARCHAR2(300),
	PRIMARY KEY (ID)
);

CREATE TABLE AREA_AMENAZADA (
    ID VARCHAR2(8) NOT NULL,
    NOMBRE VARCHAR(40),
    DETALLE_AMENAZA VARCHAR2(400),
    AMENAZA_RIESGO_ID VARCHAR2(8),
    AREA_PROTEGIDA_ID VARCHAR2(8),
    PRIMARY KEY (ID),
    FOREIGN KEY (AMENAZA_RIESGO_ID) REFERENCES AMENAZA_RIESGO(ID) ON DELETE SET NULL,
    FOREIGN KEY (AREA_PROTEGIDA_ID) REFERENCES AREA_PROTEGIDA(ID) ON DELETE SET NULL
);

CREATE TABLE ESTADO_CONSERVACION (
    ID VARCHAR2(8) NOT NULL,
    ESTADO VARCHAR2(150) UNIQUE,
    DESCRIPCION VARCHAR2(200),
    PRIMARY KEY (ID)
);

CREATE TABLE HABITAT (
    ID VARCHAR2(8) NOT NULL,
    NOMBRE_HABITAT VARCHAR2(100) UNIQUE,
	PRIMARY KEY (ID)
);

CREATE TABLE OBSERVACION (
    ID VARCHAR2(20),
	FECHA_HORA DATE CHECK (FECHA_HORA > TO_DATE('1800-01-01', 'YYYY-MM-DD') AND FECHA_HORA <= TO_DATE('2024-05-01', 'YYYY-MM-DD')),
	NUMERO_INDIVIDUOS INTEGER CHECK (NUMERO_INDIVIDUOS > 0),
    NOTAS VARCHAR2(400),
    AREA_PROTEGIDA_ID VARCHAR2(8),
    UBICACION_LATITUD NUMBER(9, 6) CHECK (UBICACION_LATITUD >= -90 AND UBICACION_LATITUD <= 90),
    UBICACION_LONGITUD NUMBER(10, 6) CHECK (UBICACION_LONGITUD >= -180 AND UBICACION_LONGITUD <= 180),
    PRIMARY KEY (ID),
    FOREIGN KEY (AREA_PROTEGIDA_ID) REFERENCES AREA_PROTEGIDA(ID) ON DELETE SET NULL
);

CREATE TABLE ESPECIE (
    ID VARCHAR2(30) NOT NULL,
	NOMBRE_CIENTIFICO VARCHAR2(150),
	NOMBRE_COMUN VARCHAR2(150),
	CARACTERISTICAS_FISICAS VARCHAR2(200),
	HABITAT_ID VARCHAR2(8),
	ESTADO_CONSERVACION_ID VARCHAR2(8),
	PRIMARY KEY (ID),
    FOREIGN KEY (HABITAT_ID) REFERENCES HABITAT(ID) ON DELETE SET NULL,
    FOREIGN KEY (ESTADO_CONSERVACION_ID) REFERENCES ESTADO_CONSERVACION(ID) ON DELETE SET NULL
);

CREATE TABLE OBSERVACION_ESPECIE (
    ID VARCHAR2(8) NOT NULL,
    CANTIDAD_ESPECIE INTEGER CHECK (CANTIDAD_ESPECIE > 0),
    OBSERVACION_ID VARCHAR2(20),
    ESPECIE_ID VARCHAR2(30),
    PRIMARY KEY (ID),
    FOREIGN KEY (OBSERVACION_ID) REFERENCES OBSERVACION(ID) ON DELETE SET NULL,
    FOREIGN KEY (ESPECIE_ID) REFERENCES ESPECIE(ID) ON DELETE SET NULL
);